# This file will serve the base configurations for CI and local envrionments
version: "3.4"
services:
  selenoid:
    image: "aerokube/selenoid:1.10.7"
    container_name: selenoid
    ports:
      - "4443:4444"
    networks:
      - selenoid
    environment:
      - TZ=Asia/Kolkata
      
# this is the custom build app which contains our automation test scripts
  e2e:
    image: e2e-test
    build: . # it takes the path of the dockerfile and builds it
    depends_on:
      - selenoid
    links:
      - selenoid
    networks:
      - selenoid
    volumes:
      - "./allure-results:/usr/lib/wdio/allure-results" # volume mapping the allure results
      - "./data:/usr/lib/wdio/data"

networks:
  selenoid:
    name: selenoid
